/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("io.cucumber:cucumber-java:7.11.1")
    api("net.masterthought:cucumber-reporting:5.7.4")
    api("org.seleniumhq.selenium:selenium-java:4.8.0")
    api("io.github.bonigarcia:webdrivermanager:5.3.2")
    api("io.github.sukgu:automation:0.1.4.1")
    testImplementation("junit:junit:4.11")
    testImplementation("io.cucumber:cucumber-core:7.11.1")
    testImplementation("io.cucumber:cucumber-junit:7.11.1")
}

group = "dev.matoro"
version = "1.0.1"
description = "Bolttech-UI"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
